### ISSUE TITLE
Hidden columns should be nullable

### ISSUE THREAD

**Issue by hailam** [fumeapp/modeltyper#18]
Hidden columns like passwords should be nullable, since these will not be sent to front in normal circumstances

**Comment by tcampbPPU** [comment]
@acidjazz this brings up good point, for hidden is this where we should prepend the `?` so like a password would look like:
```ts
export interface User {
   password?: string
}
```

**Comment by acidjazz** [comment]
that makes `password` optional - what does laravel do when you hide it? make it null? or hidden?

**Comment by tcampbPPU** [comment]
the password field would never be sent with the api/payload so a hidden field should never really exist (in most cases) in the front end. But I think we can do something [here ](https://github.com/fumeapp/modeltyper/blob/master/src/Actions/WriteColumnAttribute.php#L84)if there is a `'hidden'` attribute

**Comment by acidjazz** [comment]
@tcampbPPU so then for hidden it should be your suggestion - `password?`

**Comment by tcampbPPU** [comment]
I think so. Since hidden fields would likely be undefined since they would typically never be available

**Comment by acidjazz** [comment]
Let me know if you have the time or I can get this in

**Comment by tcampbPPU** [comment]
I can get to it later this evening

**Comment by tcampbPPU** [comment]
@hailam We choose to make these as `undefined`, rather then `null` with PR #20. But if a field if both hidden and nullable (like a password) it would include both `password?: string|null`
