### ISSUE TITLE
Feature: support for generics in type

### ISSUE THREAD

**Issue by nonetallt** [fumeapp/modeltyper#22]
The current version doesn't handle generics in type correctly. Defining a type with a generic inside the interfaces array results in the generic being used inside the import statement, which obviously causes an error with typescript.

The following code:
```php
public array $interfaces = [
    'editable' => [
        'import' => '@/types/Editable.ts',
        'type' => 'Editable<TaskList>',
    ],
];
```

Results in:
```ts
import { Editable<TaskList> } from '@/types/Editable.ts'
export interface TaskList {
  // columns
  id: number
  name: string
  tracked: boolean
  user_id: number
  created_at: Date|null
  updated_at: Date|null
  // mutators
  editable: unknown
  // overrides
  editable: Editable<TaskList>
}
export type TaskLists = TaskList[]
export interface TaskListResults extends api.MetApiResults { data: TaskLists }
export interface TaskListResult extends api.MetApiResults { data: TaskList }
export interface TaskListMetApiData extends api.MetApiData { data: TaskList }
export interface TaskListResponse extends api.MetApiResponse { data: TaskListMetApiData }

``` 

The column definition inside the interface works as expected but the generic causes the import to break. This should be quite easy to fix by implemening one of the following options for example:

1) Add a key called "generics" in the interfaces array definition
2) Find strpos of `<` and substring the type when outputting the import statements (I edited my vendor to test this approach to be viable, although I only edited the console output)

On an unrelated note, it also seems unnecessary to output overridden keys twice in the interface. I suggest only applying the keys from overrides (interfaces array). Note these keys in the example:
```ts
  // mutators
  editable: unknown
  // overrides
  editable: Editable<TaskList>
  ```

**Comment by acidjazz** [comment]
@nonetallt awesome feature! happy to get on this when i get time - a PR is more than welcome as well!
