### ISSUE TITLE
Errors when a generic class exists in Models folder.

### ISSUE THREAD

**Issue by n1c** [fumeapp/modeltyper#24]
Hey team!

I bumped into an issue when using this lib, possibly because I'm doing something unexpected.

In my models folder I have some classes which other models implement, for example `/models/Generic/Choice.php` isn't actually a model that maps to a database table, it's just a model class that some "real" models implement.

This seems to have caused the generate interfaces process to get very sad. Maybe because you try to generate for all files that exist in `/models`?

Hopefully this somewhat vague information is useful in tracking down a bug! Please let me know if I can be more specific.

✌️

**Comment by acidjazz** [comment]
@n1c i think one solution to this is maybe add a feature where you can specify something like `$modelTyperIgnore = true` and then this package just bypasses it completely - we can get to it when we get time, PR's are more than appreicated!

**Comment by tcampbPPU** [comment]
What happens to that class when you use the internal Laravel model show command for that?
For example:
```bash
./artisan model:show Generic/Choice
```

**Comment by tcampbPPU** [comment]
also would be helpful to know if these are traits or classes this is happening too.

**Comment by n1c** [comment]
I made a repo here so you can see exactly the (broken) setup I was trying: https://github.com/n1c/modeltyper-test

```sh
➜  artisan model:show Generic\Choice

   ERROR  Target class [App\Models\GenericChoice] does not exist.
```

Interesting to see there it seems to strip out the `\`. There might be a mismatch of assumptions where Laravel doesn't want models to ever be in a sub-folder while modeltyper doesn't mind?

**Comment by tcampbPPU** [comment]
@n1c thanks for the example repo, yea not sure exactly whats going on with that, but I can take a look at see if I can figure out.

**Comment by tcampbPPU** [comment]
ok @n1c I believe I was able to fix, should be updating the release soon

**Comment by n1c** [comment]
Awesome, looking forward to it!

**Comment by acidjazz** [comment]
@n1c https://github.com/fumeapp/modeltyper/releases/tag/v1.2.1

**Comment by n1c** [comment]
Looks like packagist doesn't auto-update, is that something ya'll do manually?

**Comment by tcampbPPU** [comment]
yea looks like @acidjazz has to do that

**Comment by acidjazz** [comment]
done @n1c

**Comment by n1c** [comment]
Nice one, thanks team! 🥳
