### ISSUE TITLE
Relationships use the Plural interface even if plurals are disabled

### ISSUE THREAD

**Issue by n1c** [fumeapp/modeltyper#37]
Hey team, if I generate types with plurals disabled an interface's relationships will still try to use the (now disabled) plural version of the interface.

e.g.

```
export interface User {
  ...
  tokens?: PersonalAccessTokens
  ...
}
```

But `PersonalAccessTokens` isn't generated unless I specify `--plurals`

**Comment by acidjazz** [comment]
@nurdism got time to take a look?
