### ISSUE TITLE
feature request: support Laravel modules 

### ISSUE THREAD

**Issue by allanlaal** [fumeapp/modeltyper#44]
Laravel now supports modules, so my code is organized like this:

	app
		Meeting
			Models
			..
		Messages
			Models
			..
		Users
			Models
			..

can you make fumeapp/modeltyper support looking for models in app/*/Models ?

**Comment by allanlaal** [comment]
Thank you @tcampbPPU!

but it seems its not skipping route files that have no classes:

	Class "App\MyModule\Routes\api" does not exist
	
	  at vendor/fumeapp/modeltyper/src/Actions/GetModels.php:57
	     53▕                     ['\\', ''],
	     54▕                     Str::after($file->getPathname(), app_path() . DIRECTORY_SEPARATOR)
	     55▕                 );
	     56▕ 
	  ➜  57▕                 return (new ReflectionClass($class))->isSubclassOf(EloquentModel::class);
	     58▕             })
	     59▕             ->when($includedModels, function ($files, $includedModels) {
	     60▕                 return $files->filter(fn (SplFileInfo $file) => in_array($file->getBasename('.php'), $includedModels));
	     61▕             })

**Comment by tcampbPPU** [comment]
hmm strange, @allanlaal  could you provide an example of that api file you have?

**Comment by tcampbPPU** [comment]
in the mean time, I pushed out [v2.2.3](https://github.com/fumeapp/modeltyper/releases/tag/v2.2.3) which hopefully fixes it

**Comment by allanlaal** [comment]
its a classless file containing routes, v2.2.3 fixed it :)

thank you!

**Comment by ryssbowh** [comment]
Did the cli option to change the path make it to the repo ?

I'm using the laravel modules package and most of my models are outside of the app folder (`modules` folder), would be great to support it.

Thanks
