### ISSUE TITLE
I don't get any columns generated in my interfaces

### ISSUE THREAD

**Issue by polsust** [fumeapp/modeltyper#56]
### What happened?

After running :

```bash
php artisan model:typer
```

I noticed that none of the fillables of my models where outputed into the interfaces.

Laravel version: `9.51.0`
php version: `8.1.19`

----------

I tried running:

```bash
composer require doctrine/dbal
```
and it returned: 
```
curl error 60 while downloading https://repo.packagist.org/p2/doctrine/dbal~dev.json: SSL: no alternative certificate subject name matches target host
  name 'repo.packagist.org
```

### Expected Behavior

I expected to recieve the generated interfaces with my model's fillables.

example of model:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Key extends Model
{
    use HasFactory;

    protected $fillable = [
        "keyable_id",
        "keyable_type",
        "key_status_id",
        "key_type_id",
        "number",
        "description"
    ];

    public function keyable () {
        return $this->morphTo();
    }

    public function keyStatus () {
        return $this->belongsTo(KeyStatus::class);
    }

    public function keyType () {
        return $this->belongsTo(KeyType::class);
    }
}
```

example of autogenerated interface:

```ts
export interface Key {
  // relations
  keyable: Key;
  key_status: KeyStatus;
  key_type: KeyType;
}
```

### Steps To Reproduce

1. run 
```bash
composer require --dev fumeapp/modeltyper
php artisan model:typer > types.d.ts
```

**Comment by polsust** [comment]
I managed to install `doctrine/dbal` but it didn't fix my problem

**Comment by tcampbPPU** [comment]
Are you using something like SQLite and these columns are not available yet?
What happens when you run:
```bash
php artisan model:show Key
```

**Comment by tcampbPPU** [comment]
this package depends on the Laravel artisan model:show command, so if there is nothing generated from that command in that `Attributes` section, we cannot generate the type.

**Comment by polsust** [comment]
That is expected because the model doesn't have any `Attributes` but does have a few columns

**Comment by tcampbPPU** [comment]
Thats not what is meant int the Attributes section of that output, its not referring to Model Attributes (like castors and mutators). It will show both models columns and accessor, for example:
![image](https://github.com/fumeapp/modeltyper/assets/25044744/26a4c666-bb09-4c4c-9443-b99f445578be)

What this packages does it takes whatever is in the Attributes section and turns into TS type. If nothing is there it would be expected nothing is generated from the model:typer command
