### ISSUE TITLE
[BUG] Unknown cast type: hashed

### ISSUE THREAD

**Issue by n1c** [fumeapp/modeltyper#58]
### What happened?

Was testing modeltyper on a fresh Laravel repo today and I see it bumps into an issue with the 'hashed' cast type.

```
> php artisan model:typer

"Unknown cast type: hashed" // vendor/fumeapp/modeltyper/src/Actions/WriteColumnAttribute.php:85
export interface User {
  // columns
  id: number
  name: string
  email: string
  email_verified_at: string|null
  password?: unknown
  remember_token?: string|null
  created_at: string|null
  updated_at: string|null
  // mutators
  causes_problems: unknown
  // relations
  tokens: PersonalAccessToken[]
  notifications: DatabaseNotification[]
}
```

I'm assuming it's caused by this in Models\User:

```
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
```

**Comment by acidjazz** [comment]
TIL cast typed hashed - does it return like an md5 or sha256 of the value?

**Comment by tcampbPPU** [comment]
> TIL cast typed hashed - does it return like an md5 or sha256 of the value?

Same didn't know this was a thing, should be resolved with #59

**Comment by n1c** [comment]
Nice one, thanks team! I also didn't know about this until I found it by accident 😹

**Comment by tcampbPPU** [comment]
> Nice one, thanks team! I also didn't know about this until I found it by accident 😹

Np! Thanks for pointing it out, should be resolved in the latest version https://github.com/fumeapp/modeltyper/releases/tag/v2.2.6
