### ISSUE TITLE
[BUG] [LARAVEL_11] Missing types definitions in Laravel 11

### ISSUE THREAD

**Issue by ayrtonandino** [fumeapp/modeltyper#71]
### What happened?

I upgrade to Laravel 11 from 10, then i ran `php artisan model:typer` and i got a lot of type `unknowns` that previously where typed, thing like titles, booleans, etc.

Knowing that laravel 11 droped `doctrine/dbal`, i check the diferencen between `php artisan model:show` in L10 and L11, and found a lot of them.

So, to find all the differences, i created a new Model `Test` and its migration: 

```php
class Test extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'test';
}
```

```php
Schema::create('test', function (Blueprint $table) {
    $table->id();
    $table->bigInteger('bigInteger');
    $table->binary('binary');
    $table->boolean('boolean');
    $table->char('char');
    $table->dateTime('dateTime');
    $table->date('date');
    $table->decimal('decimal');
    $table->double('double');
    $table->enum('enum', [1, 2, 3, 'A', 'B']);
    $table->float('float');
    $table->integer('integer');
    $table->ipAddress('ipAddress');
    $table->json('json');
    $table->jsonb('jsonb');
    $table->longText('longText');
    $table->macAddress('macAddress');
    $table->mediumInteger('mediumInteger');
    $table->mediumText('mediumText');
    $table->rememberToken('rememberToken');
    $table->smallInteger('smallInteger');
    $table->string('string');
    $table->text('text');
    $table->time('time');
    $table->timestamp('timestamp');
    $table->year('year');
    $table->uuid('uuid');
    $table->ulid('ulid');
    $table->timestamps();
    $table->softDeletes();
});
```
With this new model, i compare the results from `model:show` and `model:typer`, this is the result:

### model:show differences (Laravel 10 -> Laravel 11)
![model:show differences](https://github.com/fumeapp/modeltyper/assets/60512432/d358795e-f8c4-4184-a719-072446bf063b)

### model:typer differences (Laravel 10 -> Laravel 11)
![model:typer differences](https://github.com/fumeapp/modeltyper/assets/60512432/51c7b8e3-87bb-49e3-b8e9-70afd54368d2)

### Expected Behavior

That ModelTyper generates the same typescript interface regardless of the Laravel version in which it is installed.

For that the followind modifications must be made to the TypescriptMappings class:

```php
public static array $mappings = [
        'array' => 'string[]',
        'bigint' => 'number',
        'bool' => 'boolean',
        'collection' => 'Record<string, unknown>',
        'date' => 'string',
        'datetime' => 'string',
        'decimal' => 'number',
        'double' => 'number',
        'encrypted' => 'string',
        'guid' => 'string',
        'hashed' => 'string',
        'json' => 'Record<string, unknown>',
        'object' => 'Record<string, unknown>',
        'text' => 'string',
        'timestamp' => 'string',

        // 'point' => 'Point', <- remove this as is not an actual typescript type

        // old for Laravel 10 and maybe some casts
        'boolean' => 'boolean',
        'float' => 'number',
        'integer' => 'number',
        'string' => 'string',

        // new for Laravel 11
        'char' => 'string',
        'double' => 'number',
        'enum' => 'string',
        'int' => 'number',
        'longtext' => 'string',
        'mediumint' => 'number',
        'mediumtext' => 'string',
        'smallint' => 'number',
        'tinyint' => 'boolean',
        'time' => 'string',
        'varchar' => 'string',
        'year' => 'number',
];
```

## Result (Laravel 10 -> Laravel 11)

With this new mappings, now ModelTyper produce this differences in the generated interface:

![new TS differences](https://github.com/fumeapp/modeltyper/assets/60512432/74542a35-3bd4-47a5-84de-d3ea5befa6ae)

**Comment by tcampbPPU** [comment]
thanks for this 🙏🏼 I will work on a fix asap when I get the time!

**Comment by ayrtonandino** [comment]
The new `$mappings` I submitted works grate, so if you swap them out, the problem is fixed.

Besides that, I would suggest adding a new key `custom_mappings` to the config, so users can extend or override the current configuration, like how the `$interfaces` array work inside the model, but in a package level.

That way people can add for example the 'Point' type back in, or set the ‘year’ type back as a string:

```php
// config/modeltyper.php
return [
    /**
     * Custom mappings allow you to add support for types that are
     * considered to be unknown, or override existing mappings.
     */
    'custom_mappings' => [
        'binary' => 'Blob',
        'point' => 'Point',
        'year' => 'string',
    ],

    /**
     * Custom relationships allows you to add support for relationships from
     * external packages that are not a part of the Laravel core. Note that
     * relationship method names are case sensitive.
     */
    'custom_relationships' => [
        'singular' => [
            // custom relationships that return a single model
            // 'belongsToThrough',
        ],
        'plural' => [
            // custom relationships that return multiple models
        ],
    ],
];
```

Then you could merge the default `$mapping` with the config like this:

```php
$mappings = array_merge(TypescriptMappings::$mappings, config('modeltyper.custom_mappings', []))
```

**Comment by tcampbPPU** [comment]
thanks again, if you wanna throw this in a PR that would be much appreciated! Otherwise its whenever i get some free time unfortunately 😅. But i will try to prioritize this!

**Comment by tcampbPPU** [comment]
check [v2.4.0](https://github.com/fumeapp/modeltyper/releases/tag/v2.4.0)
