### ISSUE TITLE
[BUG] Cant install in Laravel v11.33.0

### ISSUE THREAD

**Issue by ayrtonandino** [fumeapp/modeltyper#81]
### What happened?

After composer update to Laravel [v11.33.0](https://github.com/laravel/framework/releases/tag/v11.33.0) i got this error

 ```console
@php artisan package:discover --ansi

   Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of FumeApp\ModelTyper\Commands\ShowModelCommand::handle() must be compatible with Illuminate\Database\Console\ShowModelCommand::handle(Illuminate\Database\Eloquent\ModelInspector $modelInspector) at vendor\fumeapp\modeltyper\src\Commands\ShowModelCommand.php:31
     27▕
     28▕     /**
     29▕      * @override
     30▕      */
  ➜  31▕     public function handle()
     32▕     {
     33▕         // Override default console component factory to force parent command to return failed exit code on error.
     34▕         $this->components = new ErrorEmittingConsoleComponentFactory($this->components, $this->option('throw-exceptions')); // @phpstan-ignore-line
     35▕
```

looks like Laravel upgrade `Illuminate\Database\Console\ShowModelCommand` to extract its functionality to separate class in [#53541](https://github.com/laravel/framework/pull/53541)

for now adding `Illuminate\Database\Eloquent\ModelInspector` to the handle method works just fine for install, command runs ok, dont know if this works `ErrorEmittingConsoleComponentFactory`

```php
use Illuminate\Database\Eloquent\ModelInspector;


     /**
     * @override
     */
    public function handle(ModelInspector $modelInspector)
    {
        // Override default console component factory to force parent command to return failed exit code on error.
        $this->components = new ErrorEmittingConsoleComponentFactory($this->components, $this->option('throw-exceptions')); // @phpstan-ignore-line

        if ($this->option('custom-relationships')) {
            $customRelationships = collect(explode(',', $this->option('custom-relationships')))->map(fn($method) => trim($method));
            $this->relationMethods = array_merge($this->relationMethods, $customRelationships->toArray());
        }

        return parent::handle($modelInspector);
    }
```

### Steps To Reproduce

init new laravel >=11.33 project
install modeltyper
get composer error

**Comment by ayrtonandino** [comment]
I think a new version V3 would be good, drop the old `ModelInterface::class`, drop laravel < 11.33, upgrade larastan@v3/phpstan@v2 and implement the new `ModelInspector::class` instead off overriding the base `ShowModelCommand::class`

**Comment by tcampbPPU** [comment]
Thanks for reporting @ayrtonandino 
I like the v3 idea! but its not something I can promise to get too soon, but feel free to PR something and I can review it!
